spring:
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/todo?useSSL=false
    username: root
    password: password
  mail:
    host: smtp.gmail.com
    port: 587
    username: <USERNAME>
    password: <APP PASSWORD>
    properties:
      mail:
        smtp:
          starttls:
            enable: true
app:
  mail:
    from: <EMAIL ADDRESS>
